# setting the default shell to zsh
set -g default-command /bin/zsh

set -g base-index 1
setw -g pane-base-index 1

# reload config file
bind r source-file ~/.tmux.conf

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

bind r source-file ~/.tmux.conf
set-window-option -g mode-keys vi

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using v and h, similar to nvim
bind s split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
unbind '"'
unbind %

# vim-like pane switching
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# rebind x to kill-pane without confirmation
bind-key x kill-pane

# plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

# catpuccin config
set -g status-position top
set -g @catppuccin_flavour 'macchiato'
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "directory session date_time"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_date_time_text "%H:%M:%S"

set -g @catppuccin_directory_text "#{pane_current_path}"

set-environment -g PATH "/opt/homebrew/bin:/bin:/usr/bin"
run '~/.tmux/plugins/tpm/tpm'
